-- Add 10 new GMI Cloud models (DeepSeek V4 Pro, GPT-5.5, GLM-5/5.1, GPT Image 2, HappyHorse, Wan 2.7, Seedance 2.0)
INSERT INTO public.ai_model_catalog (
  id, endpoint_id, provider, provider_label, name, description, category, pricing_text, pricing, transport_type, media_type, workflow_type, ui_group, supports, payload_keys, requires_assets, defaults, controls, aliases, enabled, credits, time_label, sort_rank, studio_surfaces, kanvas_modes, raw_api_example, raw_payload, raw_source_block, is_default, default_rank
) VALUES
  ('gmi/deepseek-v4-pro', 'deepseek-ai/DeepSeek-V4-Pro', 'gmi-cloud', 'DeepSeek', 'DeepSeek V4 Pro', 'DeepSeek V4 Pro: hybrid Compressed + Heavily Compressed Attention for efficient long-context (1M tokens), Manifold-Constrained Hyper-Connections, trained with Muon optimizer. Strong reasoning + tool use.', 'llm', 'Input: $1.392 per 1M tokens; Output: $2.784 per 1M tokens', '{"raw": "Input: $1.392 / Output: $2.784 per 1M tokens", "inputUsdPer1M": 1.392, "outputUsdPer1M": 2.784, "credits": 0}'::jsonb, 'chat_completion', 'text', 'text-to-text', 'generation', ARRAY['prompt','messages','max_tokens','temperature','tools']::text[], ARRAY[]::text[], ARRAY[]::text[], '{}'::jsonb, '[]'::jsonb, ARRAY['deepseek-ai/DeepSeek-V4-Pro','deepseek-ai/deepseek-v4-pro','deepseek-v4-pro']::text[], TRUE, 0, '~6s', 85, ARRAY['studio:text']::text[], ARRAY[]::text[], 'curl https://api.gmi-serving.com/v1/chat/completions -H ''Authorization: Bearer $GMI_API_KEY'' -d ''{"model":"deepseek-ai/DeepSeek-V4-Pro","messages":[...]}''', '{"payloadKeys": []}'::jsonb, '', FALSE, 1000),
  ('gmi/openai-gpt-5.5', 'openai/gpt-5.5', 'gmi-cloud', 'OpenAI', 'GPT-5.5', 'OpenAI GPT-5.5 frontier model. 1M+ token context (922K input, 128K output), text + image inputs, advanced reasoning and tool use for complex professional workloads.', 'llm', 'See OpenAI pricing', '{"raw": "See OpenAI pricing", "credits": 0}'::jsonb, 'chat_completion', 'text', 'text-to-text', 'generation', ARRAY['prompt','messages','max_tokens','temperature','tools','image_url','reasoning']::text[], ARRAY[]::text[], ARRAY[]::text[], '{}'::jsonb, '[]'::jsonb, ARRAY['openai-gpt-5.5','openai/gpt-5.5']::text[], TRUE, 0, '~8s', 80, ARRAY['studio:text']::text[], ARRAY[]::text[], 'curl https://api.gmi-serving.com/v1/chat/completions -H ''Authorization: Bearer $GMI_API_KEY'' -d ''{"model":"openai/gpt-5.5","messages":[...]}''', '{"payloadKeys": []}'::jsonb, '', FALSE, 1000),
  ('gmi/glm-5', 'zai-org/GLM-5-FP8', 'gmi-cloud', 'Z.ai', 'GLM-5', 'Z.ai flagship open-source foundation model for complex systems design and long-horizon agent workflows. Production-grade coding, agentic planning, deep backend reasoning.', 'llm', 'Open-source, hosted via GMI', '{"raw": "Open-source, hosted via GMI", "credits": 0}'::jsonb, 'chat_completion', 'text', 'text-to-text', 'generation', ARRAY['prompt','messages','max_tokens','temperature','tools']::text[], ARRAY[]::text[], ARRAY[]::text[], '{}'::jsonb, '[]'::jsonb, ARRAY['glm-5','zai-org/GLM-5-FP8','zai-org/glm-5-fp8']::text[], TRUE, 0, '~6s', 88, ARRAY['studio:text']::text[], ARRAY[]::text[], 'curl https://api.gmi-serving.com/v1/chat/completions -H ''Authorization: Bearer $GMI_API_KEY'' -d ''{"model":"zai-org/GLM-5-FP8","messages":[...]}''', '{"payloadKeys": []}'::jsonb, '', FALSE, 1000),
  ('gmi/glm-5.1', 'zai-org/GLM-5.1-FP8', 'gmi-cloud', 'Z.ai', 'GLM-5.1', 'GLM-5.1: cutting-edge LLM with strong reasoning, code generation, and multilingual capabilities. Optimized for general-purpose AI applications.', 'llm', 'Open-source, hosted via GMI', '{"raw": "Open-source, hosted via GMI", "credits": 0}'::jsonb, 'chat_completion', 'text', 'text-to-text', 'generation', ARRAY['prompt','messages','max_tokens','temperature','tools']::text[], ARRAY[]::text[], ARRAY[]::text[], '{}'::jsonb, '[]'::jsonb, ARRAY['glm-5.1','zai-org/GLM-5.1-FP8','zai-org/glm-5.1-fp8']::text[], TRUE, 0, '~6s', 87, ARRAY['studio:text']::text[], ARRAY[]::text[], 'curl https://api.gmi-serving.com/v1/chat/completions -H ''Authorization: Bearer $GMI_API_KEY'' -d ''{"model":"zai-org/GLM-5.1-FP8","messages":[...]}''', '{"payloadKeys": []}'::jsonb, '', FALSE, 1000),
  ('gmi/gpt-image-2', 'gpt-image-2', 'gmi-cloud', 'OpenAI', 'GPT Image 2', 'OpenAI''s latest image model — excels at complex prompts, accurate text rendering, photorealism. Supports text-to-image and image edits with optional inpainting masks.', 'Image', 'From $0.011/image (low 1024) up to $0.250/image (high 1536)', '{"raw": "$0.011 - $0.250 per image", "usd": 0.042, "credits": 5}'::jsonb, 'request_queue', 'image', 'text-to-image', 'generation', ARRAY['prompt','size','quality','n','output_format','image','mask']::text[], ARRAY['prompt','size','quality','n','output_format','image','mask']::text[], ARRAY[]::text[], '{"size": "1024x1024", "quality": "medium", "output_format": "png", "n": 1}'::jsonb, '[{"key": "size", "label": "Size", "type": "select", "defaultValue": "1024x1024", "options": [{"label": "1024×1024", "value": "1024x1024"}, {"label": "1024×1536", "value": "1024x1536"}, {"label": "1536×1024", "value": "1536x1024"}]}, {"key": "quality", "label": "Quality", "type": "select", "defaultValue": "medium", "options": [{"label": "Low", "value": "low"}, {"label": "Medium", "value": "medium"}, {"label": "High", "value": "high"}, {"label": "Auto", "value": "auto"}]}, {"key": "output_format", "label": "Format", "type": "select", "defaultValue": "png", "options": [{"label": "PNG", "value": "png"}, {"label": "JPEG", "value": "jpeg"}]}, {"key": "n", "label": "Count", "type": "number", "defaultValue": 1, "min": 1, "max": 10, "step": 1}]'::jsonb, ARRAY['gpt-image-2']::text[], TRUE, 5, '~15s', 250, ARRAY['studio:image','kanvas:image','kanvas:edit']::text[], ARRAY['text-to-image','image-to-image']::text[], 'curl -X POST https://console.gmicloud.ai/api/v1/ie/requestqueue/apikey/requests -H ''Authorization: Bearer YOUR_API_KEY'' -d ''{"model":"gpt-image-2","payload":{"prompt":"...","size":"1024x1024","quality":"medium"}}''', '{"payloadKeys": ["prompt", "size", "quality", "n", "output_format", "image", "mask"]}'::jsonb, '', FALSE, 1000),
  ('gmi/happyhorse-1.0-t2v', 'happyhorse1.0-t2v', 'gmi-cloud', 'Wan AI', 'HappyHorse 1.0 (Text→Video)', 'Wan AI text-to-video with improved visual quality, separate resolution + aspect-ratio selection, continuous 2-15s duration, optional audio-driven generation.', 'Video', '$0.28 per second', '{"raw": "$0.28 / second", "usd": 0.28, "credits": 30}'::jsonb, 'request_queue', 'video', 'text-to-video', 'generation', ARRAY['prompt','negative_prompt','resolution','ratio','duration','audio_url','prompt_extend','watermark','seed']::text[], ARRAY['prompt','negative_prompt','resolution','ratio','duration','audio_url','prompt_extend','watermark','seed']::text[], ARRAY[]::text[], '{"resolution": "1080P", "ratio": "16:9", "duration": 5, "prompt_extend": true, "watermark": false}'::jsonb, '[{"key": "resolution", "label": "Resolution", "type": "select", "defaultValue": "1080P", "options": [{"label": "720P", "value": "720P"}, {"label": "1080P", "value": "1080P"}]}, {"key": "ratio", "label": "Aspect Ratio", "type": "select", "defaultValue": "16:9", "options": [{"label": "16:9", "value": "16:9"}, {"label": "9:16", "value": "9:16"}, {"label": "1:1", "value": "1:1"}, {"label": "4:3", "value": "4:3"}, {"label": "3:4", "value": "3:4"}]}, {"key": "duration", "label": "Duration (s)", "type": "number", "defaultValue": 5, "min": 2, "max": 15, "step": 1}, {"key": "prompt_extend", "label": "Prompt Extend", "type": "boolean", "defaultValue": true}, {"key": "watermark", "label": "Watermark", "type": "boolean", "defaultValue": false}]'::jsonb, ARRAY['happyhorse-1.0-t2v','happyhorse1.0-t2v']::text[], TRUE, 30, '~60s', 160, ARRAY['studio:video','kanvas:video']::text[], ARRAY['text-to-video']::text[], 'curl -X POST https://console.gmicloud.ai/api/v1/ie/requestqueue/apikey/requests -H ''Authorization: Bearer YOUR_API_KEY'' -d ''{"model":"happyhorse1.0-t2v","payload":{"prompt":"...","resolution":"1080P","ratio":"16:9","duration":10}}''', '{"payloadKeys": ["prompt", "negative_prompt", "resolution", "ratio", "duration", "audio_url", "prompt_extend", "watermark", "seed"]}'::jsonb, '', FALSE, 1000),
  ('gmi/happyhorse-1.0-i2v', 'happyhorse1.0-i2v', 'gmi-cloud', 'Wan AI', 'HappyHorse 1.0 (Image→Video)', 'Wan AI image-to-video. First/last frame, driving audio, first clip references. Continuous 2-15s duration.', 'Video', '$0.28 per second', '{"raw": "$0.28 / second", "usd": 0.28, "credits": 30}'::jsonb, 'request_queue', 'video', 'image-to-video', 'generation', ARRAY['prompt','negative_prompt','first_frame','last_frame','image','image_url','resolution','duration','prompt_extend','watermark','seed']::text[], ARRAY['prompt','negative_prompt','first_frame','last_frame','resolution','duration','prompt_extend','watermark','seed']::text[], ARRAY['image']::text[], '{"resolution": "1080P", "duration": 5, "prompt_extend": true, "watermark": false}'::jsonb, '[{"key": "resolution", "label": "Resolution", "type": "select", "defaultValue": "1080P", "options": [{"label": "720P", "value": "720P"}, {"label": "1080P", "value": "1080P"}]}, {"key": "duration", "label": "Duration (s)", "type": "number", "defaultValue": 5, "min": 2, "max": 15, "step": 1}, {"key": "prompt_extend", "label": "Prompt Extend", "type": "boolean", "defaultValue": true}, {"key": "watermark", "label": "Watermark", "type": "boolean", "defaultValue": false}]'::jsonb, ARRAY['happyhorse-1.0-i2v','happyhorse1.0-i2v']::text[], TRUE, 30, '~60s', 161, ARRAY['studio:video','kanvas:video']::text[], ARRAY['image-to-video']::text[], 'curl -X POST https://console.gmicloud.ai/api/v1/ie/requestqueue/apikey/requests -H ''Authorization: Bearer YOUR_API_KEY'' -d ''{"model":"happyhorse1.0-i2v","payload":{"prompt":"...","first_frame":"https://...","resolution":"1080P","duration":10}}''', '{"payloadKeys": ["prompt", "negative_prompt", "first_frame", "last_frame", "resolution", "duration", "prompt_extend", "watermark", "seed"]}'::jsonb, '', FALSE, 1000),
  ('gmi/wan-2.7-i2v', 'wan2.7-i2v', 'gmi-cloud', 'Wan AI', 'Wan 2.7 (Image→Video)', 'Wan 2.7 image-to-video with improved fidelity and temporal consistency. First/last frame, driving audio, first clip refs. 2-15s duration.', 'Video', '$0.15 per second', '{"raw": "$0.15 / second", "usd": 0.15, "credits": 18}'::jsonb, 'request_queue', 'video', 'image-to-video', 'generation', ARRAY['prompt','negative_prompt','first_frame','last_frame','image','image_url','driving_audio','first_clip','resolution','duration','prompt_extend','watermark','seed']::text[], ARRAY['prompt','negative_prompt','first_frame','last_frame','driving_audio','first_clip','resolution','duration','prompt_extend','watermark','seed']::text[], ARRAY['image']::text[], '{"resolution": "1080P", "duration": 5, "prompt_extend": true, "watermark": false}'::jsonb, '[{"key": "resolution", "label": "Resolution", "type": "select", "defaultValue": "1080P", "options": [{"label": "720P", "value": "720P"}, {"label": "1080P", "value": "1080P"}]}, {"key": "duration", "label": "Duration (s)", "type": "number", "defaultValue": 5, "min": 2, "max": 15, "step": 1}, {"key": "prompt_extend", "label": "Prompt Extend", "type": "boolean", "defaultValue": true}, {"key": "watermark", "label": "Watermark", "type": "boolean", "defaultValue": false}]'::jsonb, ARRAY['wan-2.7-i2v','wan2.7-i2v']::text[], TRUE, 18, '~50s', 155, ARRAY['studio:video','kanvas:video']::text[], ARRAY['image-to-video']::text[], 'curl -X POST https://console.gmicloud.ai/api/v1/ie/requestqueue/apikey/requests -H ''Authorization: Bearer YOUR_API_KEY'' -d ''{"model":"wan2.7-i2v","payload":{"prompt":"...","first_frame":"https://...","resolution":"1080P","duration":10}}''', '{"payloadKeys": ["prompt", "negative_prompt", "first_frame", "last_frame", "driving_audio", "first_clip", "resolution", "duration", "prompt_extend", "watermark", "seed"]}'::jsonb, '', FALSE, 1000),
  ('gmi/wan-2.7-r2v', 'wan2.7-r2v', 'gmi-cloud', 'Wan AI', 'Wan 2.7 (Reference→Video)', 'Wan 2.7 reference-to-video. Preserves character appearance, object identity, scene layout, and vocal timbre using up to 5 reference images/videos.', 'Video', '$0.15 per second', '{"raw": "$0.15 / second", "usd": 0.15, "credits": 18}'::jsonb, 'request_queue', 'video', 'image-to-video', 'generation', ARRAY['prompt','negative_prompt','first_frame','reference_image','reference_video','image','image_url','video','video_url','resolution','ratio','duration','prompt_extend','watermark','seed']::text[], ARRAY['prompt','negative_prompt','first_frame','reference_image','reference_video','resolution','ratio','duration','prompt_extend','watermark','seed']::text[], ARRAY['image']::text[], '{"resolution": "1080P", "ratio": "16:9", "duration": 5, "prompt_extend": false, "watermark": false}'::jsonb, '[{"key": "resolution", "label": "Resolution", "type": "select", "defaultValue": "1080P", "options": [{"label": "720P", "value": "720P"}, {"label": "1080P", "value": "1080P"}]}, {"key": "ratio", "label": "Aspect Ratio", "type": "select", "defaultValue": "16:9", "options": [{"label": "16:9", "value": "16:9"}, {"label": "9:16", "value": "9:16"}, {"label": "1:1", "value": "1:1"}, {"label": "4:3", "value": "4:3"}, {"label": "3:4", "value": "3:4"}]}, {"key": "duration", "label": "Duration (s)", "type": "number", "defaultValue": 5, "min": 2, "max": 15, "step": 1}, {"key": "prompt_extend", "label": "Prompt Extend", "type": "boolean", "defaultValue": false}, {"key": "watermark", "label": "Watermark", "type": "boolean", "defaultValue": false}]'::jsonb, ARRAY['wan-2.7-r2v','wan2.7-r2v']::text[], TRUE, 18, '~60s', 156, ARRAY['studio:video','kanvas:video']::text[], ARRAY['image-to-video']::text[], 'curl -X POST https://console.gmicloud.ai/api/v1/ie/requestqueue/apikey/requests -H ''Authorization: Bearer YOUR_API_KEY'' -d ''{"model":"wan2.7-r2v","payload":{"prompt":"...","reference_image":["https://..."],"resolution":"1080P","duration":10}}''', '{"payloadKeys": ["prompt", "negative_prompt", "first_frame", "reference_image", "reference_video", "resolution", "ratio", "duration", "prompt_extend", "watermark", "seed"]}'::jsonb, '', FALSE, 1000),
  ('gmi/seedance-2.0-fast', 'seedance-2-0-fast-260128', 'gmi-cloud', 'Seedance', 'Seedance 2.0 Fast', 'Next-gen video generation supporting text, first/last frame images, reference images/videos/audios. 4-15s duration up to 1080p.', 'Video', '$0.022 per second', '{"raw": "$0.022 / second", "usd": 0.022, "credits": 4}'::jsonb, 'request_queue', 'video', 'text-to-video', 'generation', ARRAY['prompt','duration','resolution','ratio','seed','watermark','generate_audio','web_search','first_frame','last_frame','reference_images','reference_videos','reference_audios','image','image_url']::text[], ARRAY['prompt','duration','resolution','ratio','seed','watermark','generate_audio','web_search','first_frame','last_frame','reference_images','reference_videos','reference_audios']::text[], ARRAY[]::text[], '{"duration": 5, "resolution": "720p", "ratio": "16:9", "watermark": false, "generate_audio": true, "web_search": false}'::jsonb, '[{"key": "resolution", "label": "Resolution", "type": "select", "defaultValue": "720p", "options": [{"label": "480p", "value": "480p"}, {"label": "720p", "value": "720p"}, {"label": "1080p", "value": "1080p"}]}, {"key": "ratio", "label": "Aspect Ratio", "type": "select", "defaultValue": "16:9", "options": [{"label": "16:9", "value": "16:9"}, {"label": "4:3", "value": "4:3"}, {"label": "1:1", "value": "1:1"}, {"label": "3:4", "value": "3:4"}, {"label": "9:16", "value": "9:16"}, {"label": "21:9", "value": "21:9"}, {"label": "adaptive", "value": "adaptive"}]}, {"key": "duration", "label": "Duration (s)", "type": "number", "defaultValue": 5, "min": 4, "max": 15, "step": 1}, {"key": "generate_audio", "label": "Generate Audio", "type": "boolean", "defaultValue": true}, {"key": "watermark", "label": "Watermark", "type": "boolean", "defaultValue": false}]'::jsonb, ARRAY['seedance-2-0-fast-260128','seedance-2.0-fast']::text[], TRUE, 4, '~30s', 150, ARRAY['studio:video','kanvas:video']::text[], ARRAY['text-to-video','image-to-video']::text[], 'curl -X POST https://console.gmicloud.ai/api/v1/ie/requestqueue/apikey/requests -H ''Authorization: Bearer YOUR_API_KEY'' -d ''{"model":"seedance-2-0-fast-260128","payload":{"prompt":"...","duration":8,"resolution":"720p"}}''', '{"payloadKeys": ["prompt", "duration", "resolution", "ratio", "seed", "watermark", "generate_audio", "web_search", "first_frame", "last_frame", "reference_images", "reference_videos", "reference_audios"]}'::jsonb, '', FALSE, 1000)
ON CONFLICT (id) DO UPDATE SET
  endpoint_id = EXCLUDED.endpoint_id,
  provider = EXCLUDED.provider,
  provider_label = EXCLUDED.provider_label,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  pricing_text = EXCLUDED.pricing_text,
  pricing = EXCLUDED.pricing,
  transport_type = EXCLUDED.transport_type,
  media_type = EXCLUDED.media_type,
  workflow_type = EXCLUDED.workflow_type,
  ui_group = EXCLUDED.ui_group,
  supports = EXCLUDED.supports,
  payload_keys = EXCLUDED.payload_keys,
  requires_assets = EXCLUDED.requires_assets,
  defaults = EXCLUDED.defaults,
  controls = EXCLUDED.controls,
  aliases = EXCLUDED.aliases,
  enabled = EXCLUDED.enabled,
  credits = EXCLUDED.credits,
  time_label = EXCLUDED.time_label,
  sort_rank = EXCLUDED.sort_rank,
  studio_surfaces = EXCLUDED.studio_surfaces,
  kanvas_modes = EXCLUDED.kanvas_modes,
  raw_api_example = EXCLUDED.raw_api_example,
  raw_payload = EXCLUDED.raw_payload,
  raw_source_block = EXCLUDED.raw_source_block,
  is_default = EXCLUDED.is_default,
  default_rank = EXCLUDED.default_rank;

NOTIFY pgrst, 'reload schema';