INSERT INTO public.ai_model_catalog (
  id,
  endpoint_id,
  provider,
  provider_label,
  name,
  description,
  category,
  pricing_text,
  pricing,
  transport_type,
  media_type,
  workflow_type,
  ui_group,
  supports,
  payload_keys,
  requires_assets,
  defaults,
  controls,
  aliases,
  enabled,
  credits,
  time_label,
  sort_rank,
  studio_surfaces,
  kanvas_modes,
  raw_api_example,
  raw_payload,
  raw_source_block,
  is_default,
  default_rank
) VALUES
(
  'gmi/seedance-2.0-t2v',
  'seedance-2-0-260128',
  'gmi-cloud',
  'bytedance',
  'Seedance 2.0',
  'Next-generation cinematic text-to-video generation from ByteDance Seedance 2.0.',
  'video',
  '$0.052/sec (video length based pricing)',
  '{"raw":"$0.052/sec","usd":0.052,"currency":"USD","credits":0}'::jsonb,
  'request_queue',
  'video',
  'text-to-video',
  'generation',
  ARRAY['prompt','duration','resolution','ratio','seed','watermark','generate_audio'],
  ARRAY['prompt','duration','resolution','ratio','seed','watermark','generate_audio'],
  ARRAY[]::text[],
  '{"duration":5,"resolution":"720p","ratio":"16:9","generate_audio":true,"watermark":false}'::jsonb,
  $$[
    {"key":"duration","label":"Duration","type":"select","defaultValue":5,"options":[{"label":"4 sec","value":4},{"label":"5 sec","value":5},{"label":"8 sec","value":8},{"label":"10 sec","value":10},{"label":"12 sec","value":12},{"label":"15 sec","value":15}]},
    {"key":"resolution","label":"Resolution","type":"select","defaultValue":"720p","options":[{"label":"480p","value":"480p"},{"label":"720p","value":"720p"},{"label":"1080p","value":"1080p"}]},
    {"key":"ratio","label":"Aspect Ratio","type":"select","defaultValue":"16:9","options":[{"label":"16:9","value":"16:9"},{"label":"4:3","value":"4:3"},{"label":"1:1","value":"1:1"},{"label":"3:4","value":"3:4"},{"label":"9:16","value":"9:16"},{"label":"21:9","value":"21:9"},{"label":"Adaptive","value":"adaptive"}]},
    {"key":"generate_audio","label":"Generate Audio","type":"boolean","defaultValue":true},
    {"key":"watermark","label":"Watermark","type":"boolean","defaultValue":false},
    {"key":"seed","label":"Seed","type":"number","min":0,"max":4294967295,"step":1}
  ]$$::jsonb,
  ARRAY['seedance-2-0-260128'],
  true,
  0,
  '~60s',
  112,
  ARRAY['studio:video','kanvas:video'],
  ARRAY['text-to-video'],
  '',
  '{"payloadKeys":["prompt","duration","resolution","ratio","seed","watermark","generate_audio"]}'::jsonb,
  'Manual Seedance 2.0 catalog entry.',
  false,
  1000
),
(
  'gmi/seedance-2.0-i2v',
  'seedance-2-0-260128',
  'gmi-cloud',
  'bytedance',
  'Seedance 2.0 I2V',
  'Seedance 2.0 image-to-video generation using a first-frame reference.',
  'video',
  '$0.052/sec (video length based pricing)',
  '{"raw":"$0.052/sec","usd":0.052,"currency":"USD","credits":0}'::jsonb,
  'request_queue',
  'video',
  'image-to-video',
  'generation',
  ARRAY['prompt','image_url','duration','resolution','ratio','seed','watermark','generate_audio'],
  ARRAY['prompt','first_frame','duration','resolution','ratio','seed','watermark','generate_audio'],
  ARRAY['image'],
  '{"duration":5,"resolution":"720p","ratio":"16:9","generate_audio":true,"watermark":false}'::jsonb,
  $$[
    {"key":"duration","label":"Duration","type":"select","defaultValue":5,"options":[{"label":"4 sec","value":4},{"label":"5 sec","value":5},{"label":"8 sec","value":8},{"label":"10 sec","value":10},{"label":"12 sec","value":12},{"label":"15 sec","value":15}]},
    {"key":"resolution","label":"Resolution","type":"select","defaultValue":"720p","options":[{"label":"480p","value":"480p"},{"label":"720p","value":"720p"},{"label":"1080p","value":"1080p"}]},
    {"key":"ratio","label":"Aspect Ratio","type":"select","defaultValue":"16:9","options":[{"label":"16:9","value":"16:9"},{"label":"4:3","value":"4:3"},{"label":"1:1","value":"1:1"},{"label":"3:4","value":"3:4"},{"label":"9:16","value":"9:16"},{"label":"21:9","value":"21:9"},{"label":"Adaptive","value":"adaptive"}]},
    {"key":"generate_audio","label":"Generate Audio","type":"boolean","defaultValue":true},
    {"key":"watermark","label":"Watermark","type":"boolean","defaultValue":false},
    {"key":"seed","label":"Seed","type":"number","min":0,"max":4294967295,"step":1}
  ]$$::jsonb,
  ARRAY['seedance-2-0-260128'],
  true,
  0,
  '~60s',
  113,
  ARRAY['studio:video','kanvas:video'],
  ARRAY['image-to-video'],
  '',
  '{"payloadKeys":["prompt","first_frame","duration","resolution","ratio","seed","watermark","generate_audio"]}'::jsonb,
  'Manual Seedance 2.0 image-to-video catalog entry.',
  false,
  1000
),
(
  'gmi/seedance-2.0-fast-t2v',
  'seedance-2-0-fast-260128',
  'gmi-cloud',
  'bytedance',
  'Seedance 2.0 Fast',
  'Faster Seedance 2.0 text-to-video generation.',
  'video',
  '$0.052/sec (video length based pricing)',
  '{"raw":"$0.052/sec","usd":0.052,"currency":"USD","credits":0}'::jsonb,
  'request_queue',
  'video',
  'text-to-video',
  'generation',
  ARRAY['prompt','duration','resolution','ratio','seed','watermark','generate_audio'],
  ARRAY['prompt','duration','resolution','ratio','seed','watermark','generate_audio'],
  ARRAY[]::text[],
  '{"duration":5,"resolution":"720p","ratio":"16:9","generate_audio":true,"watermark":false}'::jsonb,
  $$[
    {"key":"duration","label":"Duration","type":"select","defaultValue":5,"options":[{"label":"4 sec","value":4},{"label":"5 sec","value":5},{"label":"8 sec","value":8},{"label":"10 sec","value":10},{"label":"12 sec","value":12},{"label":"15 sec","value":15}]},
    {"key":"resolution","label":"Resolution","type":"select","defaultValue":"720p","options":[{"label":"480p","value":"480p"},{"label":"720p","value":"720p"},{"label":"1080p","value":"1080p"}]},
    {"key":"ratio","label":"Aspect Ratio","type":"select","defaultValue":"16:9","options":[{"label":"16:9","value":"16:9"},{"label":"4:3","value":"4:3"},{"label":"1:1","value":"1:1"},{"label":"3:4","value":"3:4"},{"label":"9:16","value":"9:16"},{"label":"21:9","value":"21:9"},{"label":"Adaptive","value":"adaptive"}]},
    {"key":"generate_audio","label":"Generate Audio","type":"boolean","defaultValue":true},
    {"key":"watermark","label":"Watermark","type":"boolean","defaultValue":false},
    {"key":"seed","label":"Seed","type":"number","min":0,"max":4294967295,"step":1}
  ]$$::jsonb,
  ARRAY['seedance-2-0-fast-260128'],
  true,
  0,
  '~35s',
  114,
  ARRAY['studio:video','kanvas:video'],
  ARRAY['text-to-video'],
  '',
  '{"payloadKeys":["prompt","duration","resolution","ratio","seed","watermark","generate_audio"]}'::jsonb,
  'Manual Seedance 2.0 Fast catalog entry.',
  false,
  1000
),
(
  'gmi/seedance-2.0-fast-i2v',
  'seedance-2-0-fast-260128',
  'gmi-cloud',
  'bytedance',
  'Seedance 2.0 Fast I2V',
  'Faster Seedance 2.0 image-to-video generation.',
  'video',
  '$0.052/sec (video length based pricing)',
  '{"raw":"$0.052/sec","usd":0.052,"currency":"USD","credits":0}'::jsonb,
  'request_queue',
  'video',
  'image-to-video',
  'generation',
  ARRAY['prompt','image_url','duration','resolution','ratio','seed','watermark','generate_audio'],
  ARRAY['prompt','first_frame','duration','resolution','ratio','seed','watermark','generate_audio'],
  ARRAY['image'],
  '{"duration":5,"resolution":"720p","ratio":"16:9","generate_audio":true,"watermark":false}'::jsonb,
  $$[
    {"key":"duration","label":"Duration","type":"select","defaultValue":5,"options":[{"label":"4 sec","value":4},{"label":"5 sec","value":5},{"label":"8 sec","value":8},{"label":"10 sec","value":10},{"label":"12 sec","value":12},{"label":"15 sec","value":15}]},
    {"key":"resolution","label":"Resolution","type":"select","defaultValue":"720p","options":[{"label":"480p","value":"480p"},{"label":"720p","value":"720p"},{"label":"1080p","value":"1080p"}]},
    {"key":"ratio","label":"Aspect Ratio","type":"select","defaultValue":"16:9","options":[{"label":"16:9","value":"16:9"},{"label":"4:3","value":"4:3"},{"label":"1:1","value":"1:1"},{"label":"3:4","value":"3:4"},{"label":"9:16","value":"9:16"},{"label":"21:9","value":"21:9"},{"label":"Adaptive","value":"adaptive"}]},
    {"key":"generate_audio","label":"Generate Audio","type":"boolean","defaultValue":true},
    {"key":"watermark","label":"Watermark","type":"boolean","defaultValue":false},
    {"key":"seed","label":"Seed","type":"number","min":0,"max":4294967295,"step":1}
  ]$$::jsonb,
  ARRAY['seedance-2-0-fast-260128'],
  true,
  0,
  '~35s',
  115,
  ARRAY['studio:video','kanvas:video'],
  ARRAY['image-to-video'],
  '',
  '{"payloadKeys":["prompt","first_frame","duration","resolution","ratio","seed","watermark","generate_audio"]}'::jsonb,
  'Manual Seedance 2.0 Fast image-to-video catalog entry.',
  false,
  1000
),
(
  'gmi/wan2.7-i2v',
  'wan2.7-i2v',
  'gmi-cloud',
  'wan',
  'Wan 2.7 I2V',
  'Image-to-video generation with higher temporal consistency and fidelity.',
  'video',
  'Pricing not available.',
  '{"raw":"Pricing not available.","credits":0}'::jsonb,
  'request_queue',
  'video',
  'image-to-video',
  'generation',
  ARRAY['prompt','image_url','resolution','duration','prompt_extend','watermark','seed'],
  ARRAY['prompt','first_frame','resolution','duration','prompt_extend','watermark','seed'],
  ARRAY['image'],
  '{"duration":5,"resolution":"1080p","prompt_extend":true,"watermark":false}'::jsonb,
  $$[
    {"key":"duration","label":"Duration","type":"select","defaultValue":5,"options":[{"label":"2 sec","value":2},{"label":"5 sec","value":5},{"label":"8 sec","value":8},{"label":"10 sec","value":10},{"label":"12 sec","value":12},{"label":"15 sec","value":15}]},
    {"key":"resolution","label":"Resolution","type":"select","defaultValue":"1080p","options":[{"label":"720p","value":"720p"},{"label":"1080p","value":"1080p"}]},
    {"key":"prompt_extend","label":"Prompt Extend","type":"boolean","defaultValue":true},
    {"key":"watermark","label":"Watermark","type":"boolean","defaultValue":false},
    {"key":"seed","label":"Seed","type":"number","min":0,"max":2147483647,"step":1}
  ]$$::jsonb,
  ARRAY['wan2.7-i2v'],
  true,
  0,
  '~55s',
  116,
  ARRAY['studio:video','kanvas:video'],
  ARRAY['image-to-video'],
  '',
  '{"payloadKeys":["prompt","first_frame","resolution","duration","prompt_extend","watermark","seed"]}'::jsonb,
  'Manual Wan 2.7 image-to-video catalog entry.',
  false,
  1000
),
(
  'gmi/wan2.7-r2v',
  'wan2.7-r2v',
  'gmi-cloud',
  'wan',
  'Wan 2.7 R2V',
  'Reference-to-video generation from a single image or video reference.',
  'video',
  'Pricing not available.',
  '{"raw":"Pricing not available.","credits":0}'::jsonb,
  'request_queue',
  'video',
  'reference-to-video',
  'generation',
  ARRAY['prompt','image_url','video_url','resolution','ratio','duration','prompt_extend','watermark','seed'],
  ARRAY['prompt','reference_image','reference_video','resolution','ratio','duration','prompt_extend','watermark','seed'],
  ARRAY['image','video'],
  '{"duration":5,"resolution":"1080p","ratio":"16:9","prompt_extend":true,"watermark":false}'::jsonb,
  $$[
    {"key":"duration","label":"Duration","type":"select","defaultValue":5,"options":[{"label":"2 sec","value":2},{"label":"5 sec","value":5},{"label":"8 sec","value":8},{"label":"10 sec","value":10},{"label":"12 sec","value":12},{"label":"15 sec","value":15}]},
    {"key":"resolution","label":"Resolution","type":"select","defaultValue":"1080p","options":[{"label":"720p","value":"720p"},{"label":"1080p","value":"1080p"}]},
    {"key":"ratio","label":"Aspect Ratio","type":"select","defaultValue":"16:9","options":[{"label":"16:9","value":"16:9"},{"label":"9:16","value":"9:16"},{"label":"1:1","value":"1:1"},{"label":"4:3","value":"4:3"},{"label":"3:4","value":"3:4"}]},
    {"key":"prompt_extend","label":"Prompt Extend","type":"boolean","defaultValue":true},
    {"key":"watermark","label":"Watermark","type":"boolean","defaultValue":false},
    {"key":"seed","label":"Seed","type":"number","min":0,"max":2147483647,"step":1}
  ]$$::jsonb,
  ARRAY['wan2.7-r2v'],
  true,
  0,
  '~55s',
  117,
  ARRAY['studio:video','kanvas:video'],
  ARRAY['reference-to-video'],
  '',
  '{"payloadKeys":["prompt","reference_image","reference_video","resolution","ratio","duration","prompt_extend","watermark","seed"]}'::jsonb,
  'Manual Wan 2.7 reference-to-video catalog entry.',
  false,
  1000
),
(
  'gmi/claude-opus-4.7',
  'anthropic/claude-opus-4.7',
  'gmi-cloud',
  'anthropic',
  'Claude Opus 4.7',
  'Anthropic flagship high-intelligence model for reasoning, analysis, and coding.',
  'llm',
  'Pricing not available.',
  '{"raw":"Pricing not available.","credits":0}'::jsonb,
  'chat_completion',
  'text',
  'text-to-text',
  'generation',
  ARRAY['prompt','messages','max_tokens','temperature'],
  ARRAY[]::text[],
  ARRAY[]::text[],
  '{}'::jsonb,
  '[]'::jsonb,
  ARRAY['anthropic/claude-opus-4.7'],
  true,
  0,
  '~5s',
  41,
  ARRAY['studio:text'],
  ARRAY[]::text[],
  '',
  '{"payloadKeys":[]}'::jsonb,
  'Manual Claude Opus 4.7 catalog entry.',
  false,
  1000
),
(
  'gmi/glm-5.1',
  'zai-org/GLM-5.1-FP8',
  'gmi-cloud',
  'zai-org',
  'GLM 5.1',
  'General-purpose GLM 5.1 model for chat, reasoning, and code generation.',
  'llm',
  'Pricing not available.',
  '{"raw":"Pricing not available.","credits":0}'::jsonb,
  'chat_completion',
  'text',
  'text-to-text',
  'generation',
  ARRAY['prompt','messages','max_tokens','temperature'],
  ARRAY[]::text[],
  ARRAY[]::text[],
  '{}'::jsonb,
  '[]'::jsonb,
  ARRAY['zai-org/GLM-5.1-FP8'],
  true,
  0,
  '~3s',
  42,
  ARRAY['studio:text'],
  ARRAY[]::text[],
  '',
  '{"payloadKeys":[]}'::jsonb,
  'Manual GLM 5.1 catalog entry.',
  false,
  1000
)
ON CONFLICT (id) DO UPDATE SET
  endpoint_id = EXCLUDED.endpoint_id,
  provider = EXCLUDED.provider,
  provider_label = EXCLUDED.provider_label,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  pricing_text = EXCLUDED.pricing_text,
  pricing = EXCLUDED.pricing,
  transport_type = EXCLUDED.transport_type,
  media_type = EXCLUDED.media_type,
  workflow_type = EXCLUDED.workflow_type,
  ui_group = EXCLUDED.ui_group,
  supports = EXCLUDED.supports,
  payload_keys = EXCLUDED.payload_keys,
  requires_assets = EXCLUDED.requires_assets,
  defaults = EXCLUDED.defaults,
  controls = EXCLUDED.controls,
  aliases = EXCLUDED.aliases,
  enabled = EXCLUDED.enabled,
  credits = EXCLUDED.credits,
  time_label = EXCLUDED.time_label,
  sort_rank = EXCLUDED.sort_rank,
  studio_surfaces = EXCLUDED.studio_surfaces,
  kanvas_modes = EXCLUDED.kanvas_modes,
  raw_api_example = EXCLUDED.raw_api_example,
  raw_payload = EXCLUDED.raw_payload,
  raw_source_block = EXCLUDED.raw_source_block,
  is_default = EXCLUDED.is_default,
  default_rank = EXCLUDED.default_rank;
