INSERT INTO public.ai_model_catalog (
  id, endpoint_id, provider, provider_label, name, description,
  category, pricing_text, pricing, transport_type, media_type,
  workflow_type, ui_group, supports, payload_keys, requires_assets,
  defaults, controls, aliases, enabled, credits, time_label,
  sort_rank, studio_surfaces, kanvas_modes, raw_api_example,
  raw_payload, raw_source_block, is_default, default_rank
) VALUES (
  'gmi/ltx-fast-i2v',
  'ltx-2-fast-image-to-video',
  'gmi-cloud',
  'ltx',
  'LTX-2 Fast Image to Video',
  'Transforms a static image into a dynamic video using the LTX-2 Fast model.',
  'video',
  '$0.04/sec (1080p)',
  '{"raw": "$0.04/sec", "usd": 0.04, "currency": "USD", "credits": 0}'::jsonb,
  'request_queue',
  'video',
  'image-to-video',
  'generation',
  ARRAY['prompt','image_uri','duration','resolution','fps','generate_audio','camera_motion'],
  ARRAY['image_uri','prompt','duration','resolution','fps','generate_audio','camera_motion'],
  ARRAY['image'],
  '{"duration": 6, "resolution": "1920x1080", "fps": 25, "generate_audio": true}'::jsonb,
  '[]'::jsonb,
  ARRAY['ltx-2-fast-image-to-video'],
  true,
  0,
  '~60s',
  100,
  ARRAY['kanvas:video','studio:video'],
  ARRAY['image-to-video'],
  '',
  '{"payloadKeys":["image_uri","prompt","duration","resolution","fps","generate_audio","camera_motion"]}'::jsonb,
  '',
  true,
  10
) ON CONFLICT (id) DO UPDATE SET
  endpoint_id = EXCLUDED.endpoint_id,
  provider = EXCLUDED.provider,
  transport_type = EXCLUDED.transport_type,
  media_type = EXCLUDED.media_type,
  workflow_type = EXCLUDED.workflow_type,
  supports = EXCLUDED.supports,
  payload_keys = EXCLUDED.payload_keys,
  defaults = EXCLUDED.defaults,
  enabled = EXCLUDED.enabled,
  is_default = EXCLUDED.is_default;