ALTER TABLE public.generation_jobs
ADD COLUMN IF NOT EXISTS external_request_id TEXT,
ADD COLUMN IF NOT EXISTS project_id UUID NULL,
ADD COLUMN IF NOT EXISTS studio TEXT,
ADD COLUMN IF NOT EXISTS model_id TEXT,
ADD COLUMN IF NOT EXISTS input_assets TEXT[] NULL,
ADD COLUMN IF NOT EXISTS result_payload JSONB NULL,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now();