// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

export const SUPABASE_URL = "https://zjbiulirzrctfmakqjwk.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqYml1bGlyenJjdGZtYWtxandrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgzOTQ0NjksImV4cCI6MjA5Mzk3MDQ2OX0.Q3sYuwAXJWh_Ukdtpm3MtH6sWf-9cubFvhU7TEguCbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
